// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Order struct {
	ID         int64  `json:"id"`
	UserID     int64  `json:"user_id"`
	TotalPrice int64  `json:"total_price"`
	Status     string `json:"status"`
}

type OrderDetail struct {
	OrderID   int64  `json:"order_id"`
	ProductID int64  `json:"product_id"`
	Color     string `json:"color"`
	Quantity  int32  `json:"quantity"`
	Price     int64  `json:"price"`
}

type Product struct {
	ID          int64        `json:"id"`
	ProductName string       `json:"product_name"`
	Price       int64        `json:"price"`
	CreatedAt   time.Time    `json:"created_at"`
	ModifiedAt  time.Time    `json:"modified_at"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

type ProductCategory struct {
	ProductID int64  `json:"product_id"`
	Color     string `json:"color"`
	Quantity  int32  `json:"quantity"`
}

type UserAddress struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	AddressLine1 string    `json:"address_line1"`
	AddressLine2 string    `json:"address_line2"`
	City         string    `json:"city"`
	PostalCode   string    `json:"postal_code"`
	Country      string    `json:"country"`
	PhoneNumber  string    `json:"phone_number"`
	CreatedAt    time.Time `json:"created_at"`
	ModifiedAt   time.Time `json:"modified_at"`
}

type UserDatum struct {
	ID          int64     `json:"id"`
	Username    string    `json:"username"`
	Password    string    `json:"password"`
	FirstName   string    `json:"first_name"`
	LastName    string    `json:"last_name"`
	Role        string    `json:"role"`
	PhoneNumber string    `json:"phone_number"`
	CreatedAt   time.Time `json:"created_at"`
	ModifiedAt  time.Time `json:"modified_at"`
}

type UserPayment struct {
	ID           int64     `json:"id"`
	UserID       int64     `json:"user_id"`
	CardNo       string    `json:"card_no"`
	CardUserName string    `json:"card_user_name"`
	CreatedAt    time.Time `json:"created_at"`
	ModifiedAt   time.Time `json:"modified_at"`
}
