// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
)

type Querier interface {
	AddProduct(ctx context.Context, arg AddProductParams) (Product, error)
	AddProductCategory(ctx context.Context, arg AddProductCategoryParams) (ProductCategory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (UserDatum, error)
	CreateUserAddress(ctx context.Context, arg CreateUserAddressParams) (UserAddress, error)
	DeleteUserAddress(ctx context.Context, id int64) (UserAddress, error)
	GetProductByColor(ctx context.Context, arg GetProductByColorParams) ([]GetProductByColorRow, error)
	GetProductById(ctx context.Context, id int64) (GetProductByIdRow, error)
	GetProductByName(ctx context.Context, productName string) ([]GetProductByNameRow, error)
	GetProducts(ctx context.Context) ([]GetProductsRow, error)
	GetUserByName(ctx context.Context, username string) (UserDatum, error)
}

var _ Querier = (*Queries)(nil)
